baseURL = 'https://fengguangpeng.github.io/'
languageCode = 'en-us'
title = "Feng Guangpeng's Blog"
theme = "PaperMod"

[params]
    env = "production"
    title = "Feng Guangpeng's Blog"
    description = "Personal blog of Feng Guangpeng, recording thoughts on life, tech and beyond."
    author = "Feng Guangpeng"
    
    defaultTheme = "light"
    disableThemeToggle = false
    DateFormat = "2006/01/02 15:04"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    comments = true

    [params.profileMode]
        enabled = false

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "ARTICLES"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "SEARCH"
        url = "/search/"
        weight = 20

[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
